/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import covoiturage.Site;
import covoiturage.Utilisateur;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author tibse
 */
public class FAccueil extends javax.swing.JFrame {

    private FProposerTrajet fPropTraj;
    private FRechercherTrajet fRechTraj;
    private FLaisserAvis fLaisserAvis;
    private FMessage fmsg;
    private FParametresConducteur fparamcond;
    private FParametresPassager fparampassa;
    private FLesAvis favis;
    private FAdmin fadmin;
    private FAvis faviscond;
    private FApropos fapropos;
    private FPhoto fphoto;
    private FBienvenu fbien;
    private FOptionConducteur fopcond;
    private Site leSite;
    private Color gris;


    /**
     * Creates new form FParamètresConducteur
     *
     * @throws java.io.IOException
     */
    public FAccueil() throws IOException {
        initComponents();
        fPropTraj = new FProposerTrajet(this, false);
        fRechTraj = new FRechercherTrajet(this, false);
        fLaisserAvis = new FLaisserAvis(this, false);
        fmsg = new FMessage(this, false);
   
        fparamcond = new FParametresConducteur(this, false);
        fparampassa = new FParametresPassager(this, false);
        favis = new FLesAvis(this, false);
        fadmin = new FAdmin(this, false);
        faviscond = new FAvis(this, false);
        fapropos = new FApropos(this, false);
        fphoto = new FPhoto(this, false);
        fbien = new FBienvenu(this, false);
        fopcond = new FOptionConducteur(this, false);
        leSite = new Site("BlaBlaCarpe");
        leSite.charger();
        LVehicule.setEnabled(false);
        TFVehicule.setEnabled(false);
        gris = TFMail.getForeground();
        fbien.setVisible(true);
        

    }

  

    /**
     *
     * @return
     */
    public FOptionConducteur getFopcond() {
        return fopcond;
    }

    /**
     *
     * @return
     */
    public Site getLeSite() {
        return leSite;
    }

    /**
     *
     * @return
     */
    public FBienvenu getFbien() {
        return fbien;
    }

    /**
     *
     * @return
     */
    public Color getGris() {
        return gris;
    }

    /**
     *
     * @return
     */
    public FAdmin getfadmin() {
        return fadmin;
    }

    /**
     *
     * @return
     */
    public FLesAvis getfavis() {
        return favis;
    }

    /**
     *
     * @return
     */
    public FAvis getfaviscond() {
        return faviscond;
    }

    /**
     *
     * @return
     */
    public FApropos getfapropos() {
        return fapropos;
    }

    /**
     *
     * @return
     */
    public FParametresPassager getfparampassa() {
        return fparampassa;
    }

    /**
     *
     * @return
     */
    public FProposerTrajet getfPropTraj() {
        return fPropTraj;
    }

    /**
     *
     * @return
     */
    public FRechercherTrajet getfRechTraj() {
        return fRechTraj;
    }

    /**
     *
     * @return
     */
    public FLaisserAvis getfLaisserAvis() {
        return fLaisserAvis;
    }

    /**
     *
     * @return
     */
    public FMessage getfmsg() {
        return fmsg;
    }

    /**
     *
     * @return
     */
    public FParametresConducteur getfparamcond() {
        return fparamcond;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Bquitter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LConnexion = new javax.swing.JLabel();
        LNomUtilisateur = new javax.swing.JLabel();
        TFMailConnex = new javax.swing.JTextField();
        LNomUtilisateur5 = new javax.swing.JLabel();
        TFMdpConnex = new javax.swing.JPasswordField();
        RBConducteur1 = new javax.swing.JRadioButton();
        RBPassager1 = new javax.swing.JRadioButton();
        RBAdmin = new javax.swing.JRadioButton();
        BConnexion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LNomUtilisateur4 = new javax.swing.JLabel();
        TFNomUtilisateur = new javax.swing.JTextField();
        LInscription = new javax.swing.JLabel();
        LNomUtilisateur1 = new javax.swing.JLabel();
        TFMail = new javax.swing.JTextField();
        LNomUtilisateur3 = new javax.swing.JLabel();
        TFMdp1 = new javax.swing.JPasswordField();
        LNomUtilisateur2 = new javax.swing.JLabel();
        TFMdp2 = new javax.swing.JPasswordField();
        RBConducteur = new javax.swing.JRadioButton();
        RBPassager = new javax.swing.JRadioButton();
        LVehicule = new javax.swing.JLabel();
        TFVehicule = new javax.swing.JTextField();
        BInscription1 = new javax.swing.JButton();
        BPhoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LNomSite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
        });

        Bquitter.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        Bquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Quit 32.png"))); // NOI18N
        Bquitter.setText(" Quitter");
        Bquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BquitterActionPerformed(evt);
            }
        });

        LConnexion.setFont(new java.awt.Font("Segoe WP SemiLight", 1, 35)); // NOI18N
        LConnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_connect_1115552.png"))); // NOI18N
        LConnexion.setText("Connexion");

        LNomUtilisateur.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LNomUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_Mail_733463.png"))); // NOI18N
        LNomUtilisateur.setText("Mail");

        TFMailConnex.setForeground(new java.awt.Color(204, 204, 204));
        TFMailConnex.setText("Entrez votre adresse email");
        TFMailConnex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFMailConnexMouseClicked(evt);
            }
        });
        TFMailConnex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMailConnexKeyPressed(evt);
            }
        });

        LNomUtilisateur5.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LNomUtilisateur5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_password_2631120.png"))); // NOI18N
        LNomUtilisateur5.setText("Mot de passe");

        buttonGroup2.add(RBConducteur1);
        RBConducteur1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        RBConducteur1.setSelected(true);
        RBConducteur1.setText("Conducteur");

        buttonGroup2.add(RBPassager1);
        RBPassager1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        RBPassager1.setText("Passager");
        RBPassager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPassager1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBAdmin);
        RBAdmin.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        RBAdmin.setText("Admin");

        BConnexion.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        BConnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BConnexion.setText(" Connexion");
        BConnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RBAdmin)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(RBPassager1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(BConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TFMailConnex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNomUtilisateur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNomUtilisateur5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFMdpConnex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(LConnexion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBConducteur1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(134, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LConnexion)
                .addGap(19, 19, 19)
                .addComponent(LNomUtilisateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFMailConnex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LNomUtilisateur5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFMdpConnex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RBConducteur1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RBPassager1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(BConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LNomUtilisateur4.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LNomUtilisateur4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_User_415727.png"))); // NOI18N
        LNomUtilisateur4.setText("Nom d'utilisateur");

        TFNomUtilisateur.setForeground(new java.awt.Color(204, 204, 204));
        TFNomUtilisateur.setText("Entrez votre nom d'utilisateur");
        TFNomUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFNomUtilisateurMouseClicked(evt);
            }
        });
        TFNomUtilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNomUtilisateurKeyPressed(evt);
            }
        });

        LInscription.setFont(new java.awt.Font("Segoe WP SemiLight", 1, 35)); // NOI18N
        LInscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_register_3194805.png"))); // NOI18N
        LInscription.setText(" Inscription");

        LNomUtilisateur1.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LNomUtilisateur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_Mail_733463.png"))); // NOI18N
        LNomUtilisateur1.setText("Mail");

        TFMail.setForeground(new java.awt.Color(204, 204, 204));
        TFMail.setText("Entrez votre adresse email");
        TFMail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TFMail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFMailMouseClicked(evt);
            }
        });
        TFMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMailKeyPressed(evt);
            }
        });

        LNomUtilisateur3.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LNomUtilisateur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_password_2631120.png"))); // NOI18N
        LNomUtilisateur3.setText("Mot de passe");

        LNomUtilisateur2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 25)); // NOI18N
        LNomUtilisateur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_password_2631120.png"))); // NOI18N
        LNomUtilisateur2.setText("Confirmez le mot de passe");

        TFMdp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMdp2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBConducteur);
        RBConducteur.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        RBConducteur.setText("Conducteur");
        RBConducteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBConducteurActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBPassager);
        RBPassager.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        RBPassager.setSelected(true);
        RBPassager.setText("Passager");
        RBPassager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPassagerActionPerformed(evt);
            }
        });

        LVehicule.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 25)); // NOI18N
        LVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_Car_5375.png"))); // NOI18N
        LVehicule.setText("Véhicule");

        TFVehicule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TFVehicule.setForeground(new java.awt.Color(204, 204, 204));
        TFVehicule.setText("Entrez votre véhicule");
        TFVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFVehiculeMouseClicked(evt);
            }
        });
        TFVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFVehiculeActionPerformed(evt);
            }
        });
        TFVehicule.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFVehiculeKeyPressed(evt);
            }
        });

        BInscription1.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        BInscription1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BInscription1.setText(" Inscription");
        BInscription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInscription1ActionPerformed(evt);
            }
        });

        BPhoto.setFont(new java.awt.Font("Segoe WP SemiLight", 1, 12)); // NOI18N
        BPhoto.setText("Ajouter une photo de profil");
        BPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LVehicule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBPassager)
                    .addComponent(RBConducteur))
                .addGap(80, 80, 80))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LInscription)
                    .addComponent(LNomUtilisateur4)
                    .addComponent(LNomUtilisateur1)
                    .addComponent(TFMail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNomUtilisateur3)
                    .addComponent(TFMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNomUtilisateur2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BInscription1)
                        .addGap(41, 41, 41)
                        .addComponent(BPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TFVehicule, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFMdp2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LInscription)
                .addGap(18, 18, 18)
                .addComponent(LNomUtilisateur4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNomUtilisateur1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNomUtilisateur3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNomUtilisateur2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFMdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LVehicule)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(RBConducteur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBPassager)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BInscription1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 100));

        LNomSite.setFont(new java.awt.Font("Avenir LT Std 55 Roman", 0, 70)); // NOI18N
        LNomSite.setForeground(new java.awt.Color(255, 255, 255));
        LNomSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Magicarpe_petit.png"))); // NOI18N
        LNomSite.setText("BlablaCarpe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNomSite, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LNomSite, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bquitter, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bquitter)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBPassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPassagerActionPerformed
        LVehicule.setEnabled(false);
        TFVehicule.setEnabled(false);
    }//GEN-LAST:event_RBPassagerActionPerformed

    private void BConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConnexionActionPerformed

        boolean connex;
        String mail = TFMailConnex.getText();
        String mdp = TFMdpConnex.getText();
        if (RBAdmin.isSelected()) {
            if (leSite.connexionAdmin(mail, mdp)) {
                this.setVisible(false);
                fadmin.initialiser(); //init la fenêtre d'après
                fadmin.setVisible(true);
                fadmin.initialiserBouton(false);
            } else {
                JOptionPane.showMessageDialog(this, " ERREUR \nVous n'êtes pas connecté.\nMail ou mot de passe incorrecte. ");//popup
            }
        } else {
            if (getTypeUser2()) {
                connex = leSite.connexionConducteur(mail, mdp); //récup valeur connexionCOnd
            } else {
                connex = leSite.connexionPassager(mail, mdp); //récup valeur connexionPass
            }
            if (connex) {//la connexion a fonctionné
                this.setVisible(false);
                if (getTypeUser2()) {//c'est un conducteur
                    this.flushChamp();
                    if (leSite.messagesNonLus() != 0) {//l'utilisateur a des messages on l'envoie sur sa page de messages d'abord
                        this.fmsg.initialiser(); //init la fenêtre d'après
                        this.fmsg.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Bonjour " + leSite.getActivUser().getNom() + " !\nVous avez " + leSite.messagesNonLus() + " messages non lus.");//popup
                    } else {
                        fPropTraj.setVisible(true);//renvoi sur la page de proposer trajet pour un conducteur
                    }
                } else {//un passager
                    this.flushChamp();
                    if (leSite.messagesNonLus() != 0) {//l'utilisateur a des messages on l'envoie sur sa page de messages d'abord
                        this.fmsg.initialiser();//init la fenêtre d'après
                        this.fmsg.setVisible(true);
                        JOptionPane.showMessageDialog(this, "Bonjour " + leSite.getActivUser().getNom() + " !\nVous avez " + leSite.messagesNonLus() + " messages non lus.");//popup
                    } else {
                        fRechTraj.desinit();
                        fRechTraj.setBEnvoyer(false);
                        fRechTraj.setLabMsg(false);
                        fRechTraj.setTFContact(false);
                        fRechTraj.setBcontact(false);
                        fRechTraj.setVisible(true);//renvoi sur la page de recher une trajet pour un passager 
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, " ERREUR \nVous n'êtes pas connecté.\nMail ou mot de passe incorrecte. ");//popup
            }
        }
        this.desinit();
        
       
    }//GEN-LAST:event_BConnexionActionPerformed

    private void BInscription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInscription1ActionPerformed
        String nom = TFNomUtilisateur.getText();
        String mdp = TFMdp1.getText();
        String mail = TFMail.getText();
        if (TFMdp1.getText().equals(TFMdp2.getText()) && fphoto.getPdp() != null) {
            if (getTypeUser1()) {//true = conducteur
                String vehicule = TFVehicule.getText();
                leSite.inscription(mail, mdp, nom, vehicule, fphoto.getPdp());//conducteur
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "BRAVO ! Vous êtes inscrit maintenant connectez vous M. " + nom);//popup
                this.flushChamp();
                this.desinit();
                this.setVisible(true);
            } else {
                leSite.inscription(mail, mdp, nom, fphoto.getPdp());//passager
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "BRAVO ! Vous êtes inscrit maintenant connectez vous M. " + nom);//popup
                this.flushChamp();
                this.desinit();
                this.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, " ERREUR \nMots de passes différents, ou photo de profil non séléctionnée.");
            TFMdp1.setText("");
            TFMdp2.setText("");

        }
    }//GEN-LAST:event_BInscription1ActionPerformed

    /**
     *
     */
    public void flushChamp() {//nettoie les champs
        TFVehicule.setText("");
        TFNomUtilisateur.setText("");
        TFMdp1.setText("");
        TFMail.setText("");
        TFMailConnex.setText("");
        TFMdpConnex.setText("");
        TFMdp2.setText("");
    }

    /**
     *
     * @return
     */
    public boolean getTypeUser1() {
        if (RBConducteur.isSelected()) {
            return true;
        } else if (RBPassager.isSelected()) {
            return false;
        }
        return false;
    }

    /**
     *
     * @return
     */
    public boolean getTypeUser2() {
        if (RBConducteur1.isSelected()) {
            return true;
        } else if (RBPassager1.isSelected()) {
            return false;
        }
        return false;
    }

    private void RBPassager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPassager1ActionPerformed

    }//GEN-LAST:event_RBPassager1ActionPerformed

    private void BquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BquitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BquitterActionPerformed

    private void TFVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFVehiculeActionPerformed

    }//GEN-LAST:event_TFVehiculeActionPerformed

    private void RBConducteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBConducteurActionPerformed
        LVehicule.setEnabled(true);
        TFVehicule.setEnabled(true);
    }//GEN-LAST:event_RBConducteurActionPerformed

    private void BPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhotoActionPerformed
        fphoto.setVisible(true);
    }//GEN-LAST:event_BPhotoActionPerformed

    private void TFNomUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFNomUtilisateurMouseClicked
        if (TFNomUtilisateur.getForeground() != Color.black) {
            TFNomUtilisateur.setText("");
        }
    }//GEN-LAST:event_TFNomUtilisateurMouseClicked

    private void TFMailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFMailMouseClicked
        if (TFMail.getForeground() != Color.black) {
            TFMail.setText("");
        }
    }//GEN-LAST:event_TFMailMouseClicked

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeiconified

    private void TFMdp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMdp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMdp2ActionPerformed

    private void TFVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFVehiculeMouseClicked
        if (TFVehicule.getForeground() != Color.black) {
            TFVehicule.setText("");
        }
    }//GEN-LAST:event_TFVehiculeMouseClicked

    private void TFMailConnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFMailConnexMouseClicked
        if (TFMailConnex.getForeground() != Color.black) {
            TFMailConnex.setText("");
        }
    }//GEN-LAST:event_TFMailConnexMouseClicked

    private void TFMailConnexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMailConnexKeyPressed
        TFMailConnex.setForeground(Color.black);
    }//GEN-LAST:event_TFMailConnexKeyPressed

    private void TFNomUtilisateurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNomUtilisateurKeyPressed
        TFNomUtilisateur.setForeground(Color.black);
    }//GEN-LAST:event_TFNomUtilisateurKeyPressed

    private void TFMailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMailKeyPressed
        TFMail.setForeground(Color.black);
    }//GEN-LAST:event_TFMailKeyPressed

    private void TFVehiculeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFVehiculeKeyPressed
        TFVehicule.setForeground(Color.black);
    }//GEN-LAST:event_TFVehiculeKeyPressed

    /**
     *
     */
    public void desinit() {
        TFVehicule.setText("Entrez votre véhicule");
        TFVehicule.setForeground(gris);
        TFMailConnex.setText("Entrez votre adresse email");
        TFMailConnex.setForeground(gris);
        TFNomUtilisateur.setText("Entrez votre nom d'utilisateur");
        TFNomUtilisateur.setForeground(gris);
        TFMail.setText("Entrez votre adresse email");
        TFMail.setForeground(gris);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FAccueil().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FAccueil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConnexion;
    private javax.swing.JButton BInscription1;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton Bquitter;
    private javax.swing.JLabel LConnexion;
    private javax.swing.JLabel LInscription;
    private javax.swing.JLabel LNomSite;
    private javax.swing.JLabel LNomUtilisateur;
    private javax.swing.JLabel LNomUtilisateur1;
    private javax.swing.JLabel LNomUtilisateur2;
    private javax.swing.JLabel LNomUtilisateur3;
    private javax.swing.JLabel LNomUtilisateur4;
    private javax.swing.JLabel LNomUtilisateur5;
    private javax.swing.JLabel LVehicule;
    private javax.swing.JRadioButton RBAdmin;
    private javax.swing.JRadioButton RBConducteur;
    private javax.swing.JRadioButton RBConducteur1;
    private javax.swing.JRadioButton RBPassager;
    private javax.swing.JRadioButton RBPassager1;
    private javax.swing.JTextField TFMail;
    private javax.swing.JTextField TFMailConnex;
    private javax.swing.JPasswordField TFMdp1;
    private javax.swing.JPasswordField TFMdp2;
    private javax.swing.JPasswordField TFMdpConnex;
    private javax.swing.JTextField TFNomUtilisateur;
    private javax.swing.JTextField TFVehicule;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
