/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import covoiturage.Avis;
import java.util.ArrayList;
import javax.swing.JList;

/**
 *
 * @author tibse
 */
public class FAvis extends javax.swing.JDialog {

    /**
     * Creates new form AvisConducteur
     *
     * @param parent
     * @param modal
     */
    public FAvis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     *
     */
    public ArrayList<Avis> listeAvis;

    /**
     *
     */
    public Avis avis;

    /**
     *
     */
    public void initialiser() {
        LNote1.setEnabled(false);
        LNote2.setEnabled(false);
        LNote3.setEnabled(false);
        LNote4.setEnabled(false);
        LNote5.setEnabled(false);
        ((FAccueil) getParent()).getLeSite().affichageAvisUser(LAvis);
        listeAvis = ((FAccueil) getParent()).getLeSite().getActivUser().getTabAvis();
    }

    /**
     *
     */
    public void initialiserAvis() {
        if (listeAvis.isEmpty() == false && LAvis.getSelectedIndex() >= 0) {
            avis = listeAvis.get(LAvis.getSelectedIndex());
            if (((FAccueil) getParent()).getTypeUser2()) {
                ((FAccueil) getParent()).getLeSite().rechercherPassager(avis.getAuteur()).getPdp().afficher(LPhoto);
            } else {
                ((FAccueil) getParent()).getLeSite().rechercherConducteur(avis.getAuteur()).getPdp().afficher(LPhoto);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LAvis = new javax.swing.JList<>();
        BRetour = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LNote1 = new javax.swing.JLabel();
        LNote2 = new javax.swing.JLabel();
        LNote3 = new javax.swing.JLabel();
        LNote4 = new javax.swing.JLabel();
        LNote5 = new javax.swing.JLabel();
        LPhoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LAuteur1 = new javax.swing.JLabel();
        TAcontenu = new javax.swing.JScrollPane();
        TAContenu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LAvis.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 20)); // NOI18N
        LAvis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LAvisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(LAvis);

        BRetour.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        BRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/retour Black 32.png"))); // NOI18N
        BRetour.setText("Retour");
        BRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetourActionPerformed(evt);
            }
        });

        LNote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile.png"))); // NOI18N
        LNote1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile Vide 32.png"))); // NOI18N

        LNote2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile.png"))); // NOI18N
        LNote2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile Vide 32.png"))); // NOI18N

        LNote3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile.png"))); // NOI18N
        LNote3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile Vide 32.png"))); // NOI18N

        LNote4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile.png"))); // NOI18N
        LNote4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile Vide 32.png"))); // NOI18N

        LNote5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile.png"))); // NOI18N
        LNote5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile Vide 32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LNote1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNote2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNote3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNote4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNote5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNote2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNote1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNote3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNote4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNote5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(287, 100));

        jLabel1.setFont(new java.awt.Font("Avenir LT Std 55 Roman", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vos avis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        jLabel2.setText("Votre liste d'avis : ");

        LAuteur1.setFont(new java.awt.Font("Avenir LT Std 45 Book", 0, 20)); // NOI18N

        TAContenu.setColumns(20);
        TAContenu.setRows(5);
        TAcontenu.setViewportView(TAContenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAcontenu, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LAuteur1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 991, Short.MAX_VALUE)
                .addComponent(BRetour))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LAuteur1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TAcontenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)))
                .addComponent(BRetour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetourActionPerformed
        this.setVisible(false);
        if (((FAccueil) getParent()).getTypeUser2()) {//c'est un conducteur
            ((FAccueil) getParent()).getfparamcond().setVisible(true);
        } else {//pasager
            ((FAccueil) getParent()).getfparampassa().setVisible(true);
        }

    }//GEN-LAST:event_BRetourActionPerformed

    private void LAvisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LAvisValueChanged
        this.initialiserAvis();
        if (LAvis.getSelectedIndex() != -1) {

            LAuteur1.setText(avis.getAuteur());
            TAContenu.setText(avis.getTexte());
            int Note = avis.getNote();
            switch (Note) {
                case 0:
                    LNote1.setEnabled(false);
                    LNote2.setEnabled(false);
                    LNote3.setEnabled(false);
                    LNote4.setEnabled(false);
                    LNote5.setEnabled(false);
                    break;
                case 1:
                    LNote1.setEnabled(true);
                    LNote2.setEnabled(false);
                    LNote3.setEnabled(false);
                    LNote4.setEnabled(false);
                    LNote5.setEnabled(false);
                    break;
                case 2:
                    LNote1.setEnabled(true);
                    LNote2.setEnabled(true);
                    LNote3.setEnabled(false);
                    LNote4.setEnabled(false);
                    LNote5.setEnabled(false);
                    break;
                case 3:
                    LNote1.setEnabled(true);
                    LNote2.setEnabled(true);
                    LNote3.setEnabled(true);
                    LNote4.setEnabled(false);
                    LNote5.setEnabled(false);
                    break;
                case 4:
                    LNote1.setEnabled(true);
                    LNote2.setEnabled(true);
                    LNote3.setEnabled(true);
                    LNote4.setEnabled(true);
                    LNote5.setEnabled(false);
                    break;
                case 5:
                    LNote1.setEnabled(true);
                    LNote2.setEnabled(true);
                    LNote3.setEnabled(true);
                    LNote4.setEnabled(true);
                    LNote5.setEnabled(true);
                    break;
                default:
                    LNote1.setEnabled(false);
                    LNote2.setEnabled(false);
                    LNote3.setEnabled(false);
                    LNote4.setEnabled(false);
                    LNote5.setEnabled(false);
                    break;
            }
        }

    }//GEN-LAST:event_LAvisValueChanged

    /**
     *
     * @return
     */
    public JList getLAvis() {
        return LAvis;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FAvis dialog = new FAvis(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRetour;
    private javax.swing.JLabel LAuteur1;
    private javax.swing.JList<String> LAvis;
    private javax.swing.JLabel LNote1;
    private javax.swing.JLabel LNote2;
    private javax.swing.JLabel LNote3;
    private javax.swing.JLabel LNote4;
    private javax.swing.JLabel LNote5;
    private javax.swing.JLabel LPhoto;
    private javax.swing.JTextArea TAContenu;
    private javax.swing.JScrollPane TAcontenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
