/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import covoiturage.Conducteur;
import covoiturage.Photo;
import covoiturage.Trajet;
import java.awt.FileDialog;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;

/**
 *
 * @author admin
 */
public class FParametresPassager extends javax.swing.JDialog {

    /**
     * Creates new form FParametresPassager
     *
     * @param parent
     * @param modal
     */
    public FParametresPassager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private Photo pdp;
    private ArrayList<Trajet> listeTrajet;
    private Trajet trajetSelect;

    /**
     *
     */
    public void initialiser() {
        TFMdp.setVisible(false);
        BValider.setVisible(false);
        P3.setVisible(false);
        
        TAVous.setText(((FAccueil) getParent()).getLeSite().getActivUser().toString());
        ((FAccueil) getParent()).getLeSite().getActivUser().getPdp().afficher(LPhoto);
        listeTrajet = ((FAccueil) getParent()).getLeSite().rechercherlisteTrajets(LTrajet);
    }

    /**
     *
     */
    public void initialiserTrajet() {
        if (listeTrajet.isEmpty() == false && LTrajet.getSelectedIndex() >= 0) {
            trajetSelect = listeTrajet.get(LTrajet.getSelectedIndex());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BMessages = new javax.swing.JButton();
        BOu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAVous = new javax.swing.JTextArea();
        BAvis1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LTrajet = new javax.swing.JList<>();
        BAvis = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LParametres = new javax.swing.JLabel();
        BDeconnexion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LPhoto = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        TFMdp = new javax.swing.JTextField();
        BValider = new javax.swing.JButton();
        BMdp = new javax.swing.JButton();
        P3 = new javax.swing.JPanel();
        LChgPhoto = new javax.swing.JLabel();
        BFichier = new javax.swing.JButton();
        CBFichier = new javax.swing.JComboBox<>();
        LPhoto1 = new javax.swing.JLabel();
        BVal = new javax.swing.JButton();
        BPhoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BMessages.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        BMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Messages 32.png"))); // NOI18N
        BMessages.setText(" Messages");
        BMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMessagesActionPerformed(evt);
            }
        });

        BOu.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        BOu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Go 32 UI.png"))); // NOI18N
        BOu.setText(" Où allez vous ?");
        BOu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 20)); // NOI18N
        jLabel2.setText("Vous :");

        TAVous.setColumns(20);
        TAVous.setRows(5);
        jScrollPane1.setViewportView(TAVous);

        BAvis1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BAvis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile 32.png"))); // NOI18N
        BAvis1.setText(" Vos avis");
        BAvis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAvis1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Vos trajet :");

        LTrajet.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LTrajet.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LTrajetValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(LTrajet);

        BAvis.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BAvis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Etoile 32.png"))); // NOI18N
        BAvis.setText("Laisser avis");
        BAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAvisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BAvis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BAvis))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(BAvis1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BAvis1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));

        LParametres.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 70)); // NOI18N
        LParametres.setForeground(new java.awt.Color(255, 255, 255));
        LParametres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Paramètres 64 UI.png"))); // NOI18N
        LParametres.setText(" Paramètres");

        BDeconnexion.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        BDeconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Déconnexion 32 UI.png"))); // NOI18N
        BDeconnexion.setText(" Déconnexion");
        BDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LParametres, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BDeconnexion)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LParametres)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BDeconnexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TFMdp.setText("Entrez nouveau mot de passe");
        TFMdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFMdpMouseClicked(evt);
            }
        });

        BValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });

        BMdp.setText("Changer de mot de passe");
        BMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFMdp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BValider))
                            .addGroup(P4Layout.createSequentialGroup()
                                .addComponent(BMdp)
                                .addGap(0, 140, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BMdp)
                .addGap(22, 22, 22)
                .addComponent(TFMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BValider)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        LChgPhoto.setText("Choisissez une photo :");

        BFichier.setText("Ajoutez un fichier");
        BFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFichierActionPerformed(evt);
            }
        });

        CBFichier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));
        CBFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFichierActionPerformed(evt);
            }
        });

        LPhoto1.setText("jLabel3");

        BVal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValActionPerformed(evt);
            }
        });

        BPhoto.setText("Changer de photo de profil");
        BPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BFichier)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(LChgPhoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BVal)
                        .addContainerGap())
                    .addGroup(P3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BPhoto)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LChgPhoto)
                    .addComponent(CBFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(BFichier)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(P3Layout.createSequentialGroup()
                .addComponent(BPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(LPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(BVal)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BMessages)
                        .addGap(33, 33, 33)
                        .addComponent(BOu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMessages)
                    .addComponent(BOu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeconnexionActionPerformed
        this.setVisible(false);
        try {
            ((FAccueil) getParent()).getLeSite().sauvegarde();//sauvegarde dans les fichiers
        } catch (IOException ex) {
            Logger.getLogger(FMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ((FAccueil) getParent()).desinit();
        //((FAccueil) getParent()).getLeSite().flushListes();//nettoie les listes pour éviter les doublons
        ((FAccueil) getParent()).setVisible(true);//permet le connexion d'un autre utilisateur    
    }//GEN-LAST:event_BDeconnexionActionPerformed

    private void BMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMessagesActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfmsg().initialiser();//met la liste des messages à jour
        ((FAccueil) getParent()).getfmsg().setVisible(true);
    }//GEN-LAST:event_BMessagesActionPerformed

    private void BOuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOuActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfRechTraj().setVisible(true);
    }//GEN-LAST:event_BOuActionPerformed

    private void BAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAvisActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfLaisserAvis().initialiser(trajetSelect.getPilote());
        ((FAccueil) getParent()).getfLaisserAvis().setVisible(true);
    }//GEN-LAST:event_BAvisActionPerformed

    private void BAvis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAvis1ActionPerformed
//affiche les avis sur l'utilisateur courant
        this.setVisible(false);
        ((FAccueil) getParent()).getfaviscond().initialiser();
        ((FAccueil) getParent()).getfaviscond().setVisible(true);
    }//GEN-LAST:event_BAvis1ActionPerformed

    private void LTrajetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LTrajetValueChanged
        this.initialiserTrajet();
    }//GEN-LAST:event_LTrajetValueChanged

    private void TFMdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFMdpMouseClicked
        TFMdp.setText("");
    }//GEN-LAST:event_TFMdpMouseClicked

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        ((FAccueil) getParent()).getLeSite().changermdp(TFMdp.getText());
        P4.setVisible(false);
    }//GEN-LAST:event_BValiderActionPerformed

    private void BFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFichierActionPerformed
       
        FileDialog dial = new FileDialog(this, "Selectionner une photo", FileDialog.LOAD);
        dial.setVisible(true);
        String nom = dial.getFile();
        String dossier = dial.getDirectory();
        Path source = Paths.get(dossier, nom);//ou est le fichier
        Path destination = Paths.get(Photo.DOSS_IMAGES, nom);
        try {
            Files.copy(source, destination);
            CBFichier.addItem(nom);
        } catch (IOException ex) {
            Logger.getLogger(FPhoto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BFichierActionPerformed

    private void CBFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFichierActionPerformed
        pdp = new Photo((String) CBFichier.getSelectedItem());
        pdp.afficher(LPhoto1);
    }//GEN-LAST:event_CBFichierActionPerformed

    private void BPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhotoActionPerformed
        P3.setVisible(true);
    }//GEN-LAST:event_BPhotoActionPerformed

    private void BMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMdpActionPerformed
        TFMdp.setVisible(true);
        BValider.setVisible(true);
    }//GEN-LAST:event_BMdpActionPerformed

    private void BValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValActionPerformed
        ((FAccueil) getParent()).getLeSite().getActivUser().changerPhoto(pdp);
        P3.setVisible(false);
    }//GEN-LAST:event_BValActionPerformed

    /**
     *
     * @param vous
     */
    public void setTAvous(String vous) {
        TAVous.setText(vous);
    }

    /**
     *
     * @return
     */
    public JList<String> getLTrajet() {
        return LTrajet;
    }

    /**
     *
     * @return
     */
    public Conducteur getPiloteAvis() {
        return trajetSelect.getPilote();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FParametresPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FParametresPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FParametresPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FParametresPassager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FParametresPassager dialog = new FParametresPassager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAvis;
    private javax.swing.JButton BAvis1;
    private javax.swing.JButton BDeconnexion;
    private javax.swing.JButton BFichier;
    private javax.swing.JButton BMdp;
    private javax.swing.JButton BMessages;
    private javax.swing.JButton BOu;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton BVal;
    private javax.swing.JButton BValider;
    private javax.swing.JComboBox<String> CBFichier;
    private javax.swing.JLabel LChgPhoto;
    private javax.swing.JLabel LParametres;
    private javax.swing.JLabel LPhoto;
    private javax.swing.JLabel LPhoto1;
    private javax.swing.JList<String> LTrajet;
    private javax.swing.JPanel P3;
    private javax.swing.JPanel P4;
    private javax.swing.JTextArea TAVous;
    private javax.swing.JTextField TFMdp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
