/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import covoiturage.Avis;
import covoiturage.Passager;
import covoiturage.Trajet;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tibse
 */
public class FRechercherTrajet extends javax.swing.JDialog {

    private ArrayList<Trajet> listeTrajetsTrouves;
    private Trajet trajet;

    /**
     * Creates new form FAccueilPassager
     *
     * @param parent
     * @param modal
     */
    public FRechercherTrajet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     *
     */
    public void initialiser() {
        listeTrajetsTrouves = ((FAccueil) getParent()).getLeSite().rechercherTrajet(LTrajets, TFDepart.getText(), TFArrivee.getText(), LocalDate.parse(TFDate.getText(), DateTimeFormatter.ofPattern("yyyy MM dd")), CBEnfant.isSelected(), CBAnimal.isSelected());
    }
    
    /**
     *
     */
    public void initialiserTouttrajet() {
        listeTrajetsTrouves = ((FAccueil) getParent()).getLeSite().toutTrajets(LTrajets);
    }

    /**
     *
     */
    public void initialiserTrajet() {
        if (listeTrajetsTrouves.isEmpty() == false && LTrajets.getSelectedIndex() >= 0) {
            trajet = listeTrajetsTrouves.get(LTrajets.getSelectedIndex());
        }
    }

    /**
     *
     * @return
     */
    public Trajet getTrajet() {
        return trajet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LDépart = new javax.swing.JLabel();
        TFDepart = new javax.swing.JTextField();
        LArrivée = new javax.swing.JLabel();
        TFArrivee = new javax.swing.JTextField();
        LDate = new javax.swing.JLabel();
        TFDate = new javax.swing.JTextField();
        BRechercher = new javax.swing.JButton();
        CBAnimal = new javax.swing.JCheckBox();
        CBEnfant = new javax.swing.JCheckBox();
        BTrajet = new javax.swing.JButton();
        BMessages = new javax.swing.JButton();
        BParamètres = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LTrajets = new javax.swing.JList<>();
        BReserver = new javax.swing.JButton();
        LabConducteur = new javax.swing.JLabel();
        BAvis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAConducteur = new javax.swing.JTextArea();
        BContacter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LPhoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabMsg = new javax.swing.JLabel();
        BEnvoyer = new javax.swing.JButton();
        TFContact = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BDeconnexion = new javax.swing.JButton();
        LOuAllezVous = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LDépart.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        LDépart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_start_2603399.png"))); // NOI18N
        LDépart.setText("Départ");

        TFDepart.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 14)); // NOI18N
        TFDepart.setForeground(new java.awt.Color(204, 204, 204));
        TFDepart.setText("Entrez votre ville de depart");
        TFDepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFDepartMouseClicked(evt);
            }
        });
        TFDepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFDepartKeyPressed(evt);
            }
        });

        LArrivée.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        LArrivée.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_end_2331722.png"))); // NOI18N
        LArrivée.setText("Arrivée");

        TFArrivee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TFArrivee.setForeground(new java.awt.Color(204, 204, 204));
        TFArrivee.setText("Entrez votre ville d'arrivée");
        TFArrivee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFArriveeMouseClicked(evt);
            }
        });
        TFArrivee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFArriveeKeyPressed(evt);
            }
        });

        LDate.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        LDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noun_Calendar_697506.png"))); // NOI18N
        LDate.setText("Date");

        TFDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TFDate.setForeground(new java.awt.Color(204, 204, 204));
        TFDate.setText("AAAA MM JJ");
        TFDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TFDateMouseClicked(evt);
            }
        });
        TFDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFDateKeyPressed(evt);
            }
        });

        BRechercher.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 18)); // NOI18N
        BRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BRechercher.setText("Rechercher");
        BRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRechercherActionPerformed(evt);
            }
        });

        CBAnimal.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 20)); // NOI18N
        CBAnimal.setText("Animal");

        CBEnfant.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 20)); // NOI18N
        CBEnfant.setText("Enfant");
        CBEnfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEnfantActionPerformed(evt);
            }
        });

        BTrajet.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 18)); // NOI18N
        BTrajet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK 32 UI.png"))); // NOI18N
        BTrajet.setText("Voir tous les trajets");
        BTrajet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTrajetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BRechercher)
                                .addGap(18, 18, 18)
                                .addComponent(BTrajet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LDate)
                            .addComponent(LDépart)
                            .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFDepart)
                                .addComponent(TFArrivee))
                            .addComponent(LArrivée))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBEnfant)
                            .addComponent(CBAnimal))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LDépart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAnimal))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBEnfant))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LArrivée)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTrajet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BMessages.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        BMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Messages 32.png"))); // NOI18N
        BMessages.setText(" Messages");
        BMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMessagesActionPerformed(evt);
            }
        });

        BParamètres.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 35)); // NOI18N
        BParamètres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Paramètres 32 UI.png"))); // NOI18N
        BParamètres.setText(" Paramètres");
        BParamètres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParamètresActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LTrajets.setToolTipText("");
        LTrajets.setSelectedIndex(0);
        LTrajets.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LTrajetsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(LTrajets);

        BReserver.setText("Réserver");
        BReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReserverActionPerformed(evt);
            }
        });

        LabConducteur.setText("Conducteur :");

        BAvis.setText("Consulter les avis");
        BAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAvisActionPerformed(evt);
            }
        });

        TAConducteur.setColumns(20);
        TAConducteur.setRows(5);
        jScrollPane2.setViewportView(TAConducteur);

        BContacter.setText("Contacter");
        BContacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BContacterActionPerformed(evt);
            }
        });

        jLabel1.setText("Résultats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BAvis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BContacter)
                .addGap(18, 18, 18)
                .addComponent(BReserver)
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(LabConducteur)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabConducteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BReserver)
                            .addComponent(BAvis)
                            .addComponent(BContacter)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        LabMsg.setText("Message :");

        BEnvoyer.setText("Envoyer");
        BEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnvoyerActionPerformed(evt);
            }
        });

        TFContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabMsg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TFContact, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BEnvoyer)
                        .addGap(9, 9, 9))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LabMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFContact, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEnvoyer))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 51, 0));

        BDeconnexion.setFont(new java.awt.Font("Avenir LT Std 35 Light", 0, 30)); // NOI18N
        BDeconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Déconnexion 32 UI.png"))); // NOI18N
        BDeconnexion.setText(" Déconnexion");
        BDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeconnexionActionPerformed(evt);
            }
        });

        LOuAllezVous.setFont(new java.awt.Font("Segoe WP SemiLight", 0, 70)); // NOI18N
        LOuAllezVous.setForeground(new java.awt.Color(255, 255, 255));
        LOuAllezVous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Go 64 UI.png"))); // NOI18N
        LOuAllezVous.setText(" Où allez vous ? ");
        LOuAllezVous.setPreferredSize(new java.awt.Dimension(588, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOuAllezVous, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BDeconnexion)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(LOuAllezVous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BDeconnexion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BMessages)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BParamètres)
                                .addGap(16, 16, 16))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMessages)
                    .addComponent(BParamètres))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBEnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEnfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEnfantActionPerformed

    private void LTrajetsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LTrajetsValueChanged
        //a chaque fois que le passager clique sur une ligne du trajet cette méthode affiche les infos sur concducteur en dessous
        this.initialiserTrajet();
        if (trajet.getPilote().getTabTrajet().size() >= 5 && trajet.getPilote().getNoteMoyenne() >= 4) {//test si le conducteur a plus de 5 trajets et une bonne note = un bon conducteur
            JOptionPane.showMessageDialog(this, "Vous avez cliqué sur le voyage d'un conducteur aguerri et de confiance !\nVous pouvez compter sur M. " + trajet.getPilote().getNom());//popup
        }
        TAConducteur.setText(trajet.toString());//affiche les infos sur conducteur 
        trajet.getPilote().getPdp().afficher(LPhoto);//affiche sa photo
    }//GEN-LAST:event_LTrajetsValueChanged

    private void BRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRechercherActionPerformed
        try {
            this.initialiser();
            if(listeTrajetsTrouves.isEmpty()){
                JOptionPane.showMessageDialog(this,"Il n'y a pas voyage pour cette destination , départ ou date");
            }
        } catch (NullPointerException ex) {

        }
    }//GEN-LAST:event_BRechercherActionPerformed

    private void BReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReserverActionPerformed
        ((FAccueil) getParent()).getLeSite().reserverTrajet(trajet);
        BContacter.setVisible(true);
        this.desinit();
    }//GEN-LAST:event_BReserverActionPerformed

    private void BAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAvisActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfavis().initialiser();
        ((FAccueil) getParent()).getfavis().setVisible(true);
    }//GEN-LAST:event_BAvisActionPerformed

    private void BParamètresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParamètresActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfparampassa().initialiser();
        ((FAccueil) getParent()).getfparampassa().setVisible(true);
    }//GEN-LAST:event_BParamètresActionPerformed

    private void BDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeconnexionActionPerformed
        this.setVisible(false);
        try {
            ((FAccueil) getParent()).getLeSite().sauvegarde();//sauvegarde dans les fichiers
        } catch (IOException ex) {
            Logger.getLogger(FMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ((FAccueil) getParent()).desinit();
        ((FAccueil) getParent()).setVisible(true);//permet le connexion d'un autre utilisateur    
    }//GEN-LAST:event_BDeconnexionActionPerformed

    private void BContacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BContacterActionPerformed
        LabMsg.setVisible(true);
        TFContact.setVisible(true);
        BEnvoyer.setVisible(true);
    }//GEN-LAST:event_BContacterActionPerformed

    /**
     *
     * @param visi
     */
    public void setBEnvoyer(boolean visi) {
        BEnvoyer.setVisible(visi);
    }

    /**
     *
     * @param visi
     */
    public void setLabMsg(boolean visi) {
        LabMsg.setVisible(visi);
    }

    /**
     *
     * @param visi
     */
    public void setTFContact(boolean visi) {
        TFContact.setVisible(visi);
    }

    /**
     *
     * @param visi
     */
    public void setBcontact(boolean visi) {
        BContacter.setVisible(visi);
    }

    private void TFContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFContactActionPerformed

    }//GEN-LAST:event_TFContactActionPerformed

    private void BMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMessagesActionPerformed
        this.setVisible(false);
        ((FAccueil) getParent()).getfmsg().initialiser();
        ((FAccueil) getParent()).getfmsg().setVisible(true);
    }//GEN-LAST:event_BMessagesActionPerformed

    private void BEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnvoyerActionPerformed
        //creer le message et l'envoie
        //this.initialiser();
        ((FAccueil) getParent()).getLeSite().contacter(TFContact.getText(), trajet.getPilote());
        String vide[] = {""};
        LTrajets.setListData(vide);//vide la liste
        this.flushChamps();//nettoie les champs
        BEnvoyer.setVisible(false);
        LabMsg.setVisible(false);
        TFContact.setVisible(false);
        BContacter.setVisible(false);
    }//GEN-LAST:event_BEnvoyerActionPerformed

    private void TFDepartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDepartMouseClicked
        if (TFDepart.getForeground() != Color.black) {
            TFDepart.setText("");
        }
    }//GEN-LAST:event_TFDepartMouseClicked

    private void TFArriveeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFArriveeMouseClicked
        if (TFArrivee.getForeground() != Color.black) {
            TFArrivee.setText("");
        }
    }//GEN-LAST:event_TFArriveeMouseClicked

    private void TFDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFDateMouseClicked
        if (TFDate.getForeground() != Color.black) {
            TFDate.setText("");
        }
    }//GEN-LAST:event_TFDateMouseClicked

    private void TFArriveeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFArriveeKeyPressed
        TFArrivee.setForeground(Color.black);
    }//GEN-LAST:event_TFArriveeKeyPressed

    private void TFDepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDepartKeyPressed
        TFDepart.setForeground(Color.black);
    }//GEN-LAST:event_TFDepartKeyPressed

    private void TFDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDateKeyPressed
        TFDate.setForeground(Color.black);
    }//GEN-LAST:event_TFDateKeyPressed

    private void BTrajetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTrajetActionPerformed
        this.initialiserTouttrajet();
    }//GEN-LAST:event_BTrajetActionPerformed

    /**
     *
     */
    public void flushChamps() {
        TFDepart.setText("");
        TFArrivee.setText("");
        TFDate.setText("");
        TFContact.setText("");
        TAConducteur.setText("");
        String tab[] = new String[1];
        tab[0] = "";
        LTrajets.setListData(tab);
    }

    /**
     *
     */
    public void desinit() {
        TFDepart.setText("Entrez votre ville de départ");
        TFDepart.setForeground(((FAccueil) getParent()).getGris());
        TFArrivee.setText("Entrez votre ville d'arrvée");
        TFArrivee.setForeground(((FAccueil) getParent()).getGris());
        TFDate.setText("AAAA MM JJ");
        TFDate.setForeground(((FAccueil) getParent()).getGris());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRechercherTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRechercherTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRechercherTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRechercherTrajet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRechercherTrajet dialog = new FRechercherTrajet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAvis;
    private javax.swing.JButton BContacter;
    private javax.swing.JButton BDeconnexion;
    private javax.swing.JButton BEnvoyer;
    private javax.swing.JButton BMessages;
    private javax.swing.JButton BParamètres;
    private javax.swing.JButton BRechercher;
    private javax.swing.JButton BReserver;
    private javax.swing.JButton BTrajet;
    private javax.swing.JCheckBox CBAnimal;
    private javax.swing.JCheckBox CBEnfant;
    private javax.swing.JLabel LArrivée;
    private javax.swing.JLabel LDate;
    private javax.swing.JLabel LDépart;
    private javax.swing.JLabel LOuAllezVous;
    private javax.swing.JLabel LPhoto;
    private javax.swing.JList<String> LTrajets;
    private javax.swing.JLabel LabConducteur;
    private javax.swing.JLabel LabMsg;
    private javax.swing.JTextArea TAConducteur;
    private javax.swing.JTextField TFArrivee;
    private javax.swing.JTextField TFContact;
    private javax.swing.JTextField TFDate;
    private javax.swing.JTextField TFDepart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
